from fastapi import APIRouter,Depends,HTTPException
from sqlalchemy.orm import Session
from typing import Annotated
from starlette import status
from ..database import get_db
from ..services.validation_service import validate_sql
from ..services.db_execution_service import execute_sql_query
from ..schemas.chat_schema import ChatRequest, ChatResponse
from ..services.llm_service import generate_sql_from_question


router=APIRouter()

db_dependency = Annotated[Session, Depends(get_db)]

@router.post("/chat",response_model=ChatResponse)
def question_answering(request:ChatRequest,db:db_dependency):
    generated_sql = generate_sql_from_question(request.question)
    validate_query=validate_sql(generated_sql)
    if not validate_query:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST,detail="Unsafe SQL Query generated by AI. Execution aborted")
    try:
        query_results=execute_sql_query(db,generated_sql)
    except Exception as e:
        raise HTTPException(status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,detail =f"Error executing SQL query: {e}")
    print(f"Question: {request.question}")
    print(f"Generated SQL:{generated_sql}")
    return {
        "question":request.question,
        "generated_sql":generated_sql,
        "results":query_results
    }