from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.orm import Session
from typing import Annotated
from starlette import status
from ..database import get_db
from ..services.validation_service import validate_sql
from ..services.db_execution_service import execute_sql_query
from ..schemas.chat_schema import ChatRequest, ChatResponse
from ..services.llm_service import generate_sql_from_question, generate_corrected_sql

router = APIRouter()

db_dependency = Annotated[Session, Depends(get_db)]

# Maximum number of self-correction attempts after the first generation fails.
# Total LLM calls = 1 (initial) + MAX_RETRIES (corrections).
MAX_RETRIES = 3


@router.post("/chat", response_model=ChatResponse)
def question_answering(request: ChatRequest, db: db_dependency):
    # --- Initial SQL generation ---
    generated_sql = generate_sql_from_question(request.question)
    retry_count = 0

    # --- Self-correction retry loop ---
    for attempt in range(MAX_RETRIES + 1):
        # Safety check: block any destructive SQL before touching the DB
        if not validate_sql(generated_sql):
            raise HTTPException(
                status_code=status.HTTP_400_BAD_REQUEST,
                detail="Unsafe SQL query generated by AI. Execution aborted.",
            )

        try:
            query_results = execute_sql_query(db, generated_sql)

            # Success — log and return
            print(f"[chat] Question    : {request.question}")
            print(f"[chat] Final SQL   : {generated_sql}")
            print(f"[chat] Retry count : {retry_count}")

            return {
                "question": request.question,
                "generated_sql": generated_sql,
                "results": query_results,
                "retry_count": retry_count,
            }

        except Exception as db_error:
            error_message = str(db_error)
            print(f"[chat] Attempt {attempt + 1} failed: {error_message}")

            if attempt == MAX_RETRIES:
                # All retries exhausted — surface a clean error to the client
                raise HTTPException(
                    status_code=status.HTTP_422_UNPROCESSABLE_ENTITY,
                    detail=(
                        f"Could not generate a valid SQL query after "
                        f"{MAX_RETRIES} correction attempt(s). "
                        f"Last error: {error_message}"
                    ),
                )

            # Ask the model to correct itself using the exact error
            generated_sql = generate_corrected_sql(
                question=request.question,
                failed_sql=generated_sql,
                error_message=error_message,
            )
            retry_count += 1